apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: frontend
    project: expense
spec:  
  replicas: 1
  selector:
    matchLabels:
       app: frontend
       tier: frontend
       project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        project: expense
    spec:
      containers:
        - name: nginx
          image: vinayp77/frontend:1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:  # labels are used as selectors
        app: frontend
        tier: frontend
        project: expense
  ports:
    - protocol: TCP
      port: 80     # service port
      targetPort: 80  # container port          
          
