apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:  
  replicas: 1
  selector:
    matchLabels:
       app: backend
       tier: backend
       project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
        - name: nginx
          image: vinayp77/backend:1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:  # labels are used as selectors
        app: backend
        tier: backend
        project: expense
  ports:
    - protocol: TCP
      port: 3306      # service port
      targetPort: 8080  # container port          
          
