apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-s1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-s1
  resources:
    requests:
     storage: 5Gi  
    