kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-s1
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b03fcab7fd43c96b
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop" # optional