apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # labels of deployment resources
  labels:
    app: mysql
    tier: mysql
    project: expense 
spec:  
  replicas: 1
  selector:
    matchLabels:
       app: mysql
       tier: mysql
       project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
       - name: nginx
         image: vinayp77/deployments:1.0.0
         env:
          - name: MYSQL_ROOT_PASSWORD
            value: "ExpenseApp@1"
         ports:
          - containerPort: 3306